### ISSUE TITLE
Can you please change the order in which elements of persons names appear in NoSketch Engine?

### ISSUE THREAD

**Issue by AnnaParla** [ufal/ParlaMint-UA#57]
Now the patronymic names come first, which is very awkward  in Ukrainian. 
![image](https://github.com/ufal/ParlaMint-UA/assets/115141649/e952cfd7-7856-4b6f-9eb1-1374ec134301)

**Comment by matyaskopp** [comment]
I can influence this by changing the order in the `listPerson` file (shuffle surnames differently). So the current order: `patronymic surname, forename` can be in NoSketch in this order `surname patronymic, forename`. But it will not be possible to reconstruct a regular order of names: `forename patronymic surname`

**Comment by matyaskopp** [comment]
@TomazErjavec, is it possible to customize the order of names in NoSketch? I don't want to hack the data. 
I am not sure what @AnnaParla  considers as the best order. I know only a bit better option:

> surname patronymic, forename will be a bit better.

**Comment by AnnaParla** [comment]
> 
@TomazErjavec , @matyaskopp , **surname forename patronymic** would be the most user-friendly

**Comment by TomazErjavec** [comment]
Hi, I am not quite sure why this issue is being discussed here, rather than on https://github.com/clarin-eric/ParlaMint/ ?
Namely, the decision on how to format names concerns all ParlaMint corpora, not only UA. 
So, I propose to move the issue there.
To make matters even more complicated, we have the huge but unresolved issue on how to encode the names, in particular partonymics (https://github.com/clarin-eric/ParlaMint/issues/581). If we want to come to an agreement, now would be the moment, as BG has to make some changes anyway.
